export const IGNORED_FILES = [
  '**/.git/**',
  '**/.turbo/**',
  '**/build/**',
  '**/dist/**',
  '**/target/**',
  '**/out/**',
  '**/out-tsc/**',
  '**/.output/**',
  '**/tmp/**',
  '**/.tmp/**',
  '**/.cache/**',
  '**/.eslintcache/**',
  '**/node_modules/**',
  '**/.vscode/**',
  '**/.idea/**',
  '**/.idea_modules/**',
]
